version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  nodeenv:
    docker:
      - image: circleci/node:14.17.4
      - image: amazon/dynamodb-local
  python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
      aws-account:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: utils
          command: sudo apt-get update -y && sudo apt-get install -y util-linux
      - run:
          name: Deploy lambda
          command: >
            sudo yarn --frozen-lockfile && 
            script -q --flush --return ./backDeployOutput.txt -c "sls deploy --stage staging" && 
            grep -oP -m 1 'https://[\w.\-*]+?amazonaws\.com/(development|staging|production|devscratch)' ./backDeployOutput.txt > baseURL.txt
      - run:
          name: Check file
          command: ls
      - run:
          name: inspect file
          command: cat ./baseURL.txt
jobs:
  build-and-test:
    executor: nodeenv
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - aws-cli/setup:
          aws-access-key-id: FAKE_AWS_ACCESS_KEY_ID
          aws-secret-access-key: FAKE_SECRET_ACCESS_KEY
          aws-region: FAKE_AWS_REGION
      - run:
          name: Create DynamoDB tables
          command: ./local/initialiseDB.sh
      - run:
          name: Run unit tests
          command: yarn run unit

  assume-role-staging:
    executor: python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  deploy-to-staging:
    executor: nodeenv
    steps:
      - deploy-lambda:
          stage: "staging"
          aws-account: $AWS_ACCOUNT_STAGING

workflows:
  check-and-deploy-staging:
    jobs:
#       - build-and-test
      - assume-role-staging:
          context: api-assume-role-staging-context
      - deploy-to-staging:
          requires:
            - assume-role-staging
